// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1dx6JYRAMjtdEIT85moi215u3uhhsJAo',
    appId: '1:551418343218:web:6a6b976c26e31cfdf1f12b',
    messagingSenderId: '551418343218',
    projectId: 'emhomes-emapps',
    authDomain: 'emhomes-emapps.firebaseapp.com',
    storageBucket: 'emhomes-emapps.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrU3n5G3GkgXfXXeTvbFHPGvmy45JrYok',
    appId: '1:551418343218:android:3cdbcc0cd0cda7def1f12b',
    messagingSenderId: '551418343218',
    projectId: 'emhomes-emapps',
    storageBucket: 'emhomes-emapps.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDs9wGFTp0iSiAOIeVu-qL7SDZnbSa9bqQ',
    appId: '1:551418343218:ios:b61d14cd0fb25140f1f12b',
    messagingSenderId: '551418343218',
    projectId: 'emhomes-emapps',
    storageBucket: 'emhomes-emapps.appspot.com',
    iosClientId: '551418343218-gm23ibgi6v2me0e3e3tf91ebrb8m4ire.apps.googleusercontent.com',
    iosBundleId: 'com.emapps.emHome',
  );
}
